[project]
name = "clashfinder"
version = "0.1.2"
authors = ["Derek Ellis <derek@ellisd.com>"]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "arrow>=1.3.0",
    "click>=8.2.1",
]
