# This workflow fetches new Shambhala schedule data and commit and changes back to the repo

name: Shambhala schedule updates

env:
  FESTIVAL_YEAR: 2025
  FESTIVAL_DATA_PATH: festivals/shambhalafestival

on:
  workflow_dispatch:
  # This only runs on default branch
  schedule:
    - cron: "12 */6 * 6 *"      # At minute 12 past every 6th hour in June.
    - cron: "12 */6 1-23 7 *"   # At minute 12 past every 6th hour on every day-of-month from 1 through 23 in July.
  
  push:
    branches:
      - "main"
      - "gh-automation" ## For testing/development

permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    - name: Install the project
      run: uv sync --locked --all-extras --dev
    -  name: Write secrets to .env file
       run: |
        cat << EOF > ${FESTIVAL_DATA_PATH}/.env
        SESSION_KEY=${{ secrets.SHAMBHALA_SESSION_KEY }}
        EOF
    - name: Fetch latest schedule data from API
      run: |
        pushd ${FESTIVAL_DATA_PATH}
        ./${FESTIVAL_YEAR}.sh
        popd
    - name: Transform data into clashfinder text format
      run: |
        source .venv/bin/activate
        ./bin/appmiral_transform.py --tz "US/Pacific" --artists ${FESTIVAL_DATA_PATH}/${FESTIVAL_YEAR}/shambhalafestival.artists.json --stages ${FESTIVAL_DATA_PATH}/${FESTIVAL_YEAR}/shambhalafestival.stages.json > ${FESTIVAL_DATA_PATH}/${FESTIVAL_YEAR}/clashfinder.txt 
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Automated Shambhala festival data update
        file_pattern: '*.json *.txt'
  

        